name: Generate Snake Game

# Controls when the action will run
on:
  # Runs automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # Allows you to run this workflow manually
  workflow_dispatch:

# Jobs to run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3
      
      # Step 2: Generate the snake game
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.Mahi928 }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake-light.svg?palette=github-light
      
      # Step 3: Save the generated files
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
